//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidApplication.ServiceReference1 {
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="AndroidApplication.ServiceReference1", ConfigurationName="TempConvertSoap")]
public interface TempConvertSoap {
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.w3schools.com/webservices/) of message FahrenheitToCelsiusRequest does not match the default value (AndroidApplication.ServiceReference1)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertSoap/FahrenheitToCelsiusRequest", ReplyAction="http://www.w3schools.com/webservices/TempConvertSoap/FahrenheitToCelsiusResponse")]
    FahrenheitToCelsiusResponse FahrenheitToCelsius(FahrenheitToCelsiusRequest request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://www.w3schools.com/webservices/) of message CelsiusToFahrenheitRequest does not match the default value (AndroidApplication.ServiceReference1)
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertSoap/CelsiusToFahrenheitRequest", ReplyAction="http://www.w3schools.com/webservices/TempConvertSoap/CelsiusToFahrenheitResponse")]
    CelsiusToFahrenheitResponse CelsiusToFahrenheit(CelsiusToFahrenheitRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitToCelsius", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class FahrenheitToCelsiusRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string Fahrenheit;
    
    public FahrenheitToCelsiusRequest() {
    }
    
    public FahrenheitToCelsiusRequest(string Fahrenheit) {
        this.Fahrenheit = Fahrenheit;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="FahrenheitToCelsiusResponse", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class FahrenheitToCelsiusResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string FahrenheitToCelsiusResult;
    
    public FahrenheitToCelsiusResponse() {
    }
    
    public FahrenheitToCelsiusResponse(string FahrenheitToCelsiusResult) {
        this.FahrenheitToCelsiusResult = FahrenheitToCelsiusResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusToFahrenheit", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class CelsiusToFahrenheitRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string Celsius;
    
    public CelsiusToFahrenheitRequest() {
    }
    
    public CelsiusToFahrenheitRequest(string Celsius) {
        this.Celsius = Celsius;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CelsiusToFahrenheitResponse", WrapperNamespace="http://www.w3schools.com/webservices/", IsWrapped=true)]
public partial class CelsiusToFahrenheitResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string CelsiusToFahrenheitResult;
    
    public CelsiusToFahrenheitResponse() {
    }
    
    public CelsiusToFahrenheitResponse(string CelsiusToFahrenheitResult) {
        this.CelsiusToFahrenheitResult = CelsiusToFahrenheitResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface TempConvertSoapChannel : TempConvertSoap, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TempConvertSoapClient : System.ServiceModel.ClientBase<TempConvertSoap>, TempConvertSoap {
    
    public TempConvertSoapClient() {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FahrenheitToCelsiusResponse TempConvertSoap.FahrenheitToCelsius(FahrenheitToCelsiusRequest request) {
        return base.Channel.FahrenheitToCelsius(request);
    }
    
    public string FahrenheitToCelsius(string Fahrenheit) {
        FahrenheitToCelsiusRequest inValue = new FahrenheitToCelsiusRequest();
        inValue.Fahrenheit = Fahrenheit;
        FahrenheitToCelsiusResponse retVal = ((TempConvertSoap)(this)).FahrenheitToCelsius(inValue);
        return retVal.FahrenheitToCelsiusResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CelsiusToFahrenheitResponse TempConvertSoap.CelsiusToFahrenheit(CelsiusToFahrenheitRequest request) {
        return base.Channel.CelsiusToFahrenheit(request);
    }
    
    public string CelsiusToFahrenheit(string Celsius) {
        CelsiusToFahrenheitRequest inValue = new CelsiusToFahrenheitRequest();
        inValue.Celsius = Celsius;
        CelsiusToFahrenheitResponse retVal = ((TempConvertSoap)(this)).CelsiusToFahrenheit(inValue);
        return retVal.CelsiusToFahrenheitResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="AndroidApplication.ServiceReference1", ConfigurationName="TempConvertHttpPost")]
public interface TempConvertHttpPost {
    
    // CODEGEN: Generating message contract since the operation FahrenheitToCelsius is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertHttpPost/FahrenheitToCelsiusReque" +
        "st", ReplyAction="http://www.w3schools.com/webservices/TempConvertHttpPost/FahrenheitToCelsiusRespo" +
        "nse")]
    FahrenheitToCelsiusResponse1 FahrenheitToCelsius(FahrenheitToCelsiusRequest1 request);
    
    // CODEGEN: Generating message contract since the operation CelsiusToFahrenheit is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.w3schools.com/webservices/TempConvertHttpPost/CelsiusToFahrenheitReque" +
        "st", ReplyAction="http://www.w3schools.com/webservices/TempConvertHttpPost/CelsiusToFahrenheitRespo" +
        "nse")]
    CelsiusToFahrenheitResponse1 CelsiusToFahrenheit(CelsiusToFahrenheitRequest1 request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FahrenheitToCelsiusRequest1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Fahrenheit;
    
    public FahrenheitToCelsiusRequest1() {
    }
    
    public FahrenheitToCelsiusRequest1(string Fahrenheit) {
        this.Fahrenheit = Fahrenheit;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FahrenheitToCelsiusResponse1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string @string;
    
    public FahrenheitToCelsiusResponse1() {
    }
    
    public FahrenheitToCelsiusResponse1(string @string) {
        this.@string = @string;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CelsiusToFahrenheitRequest1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string Celsius;
    
    public CelsiusToFahrenheitRequest1() {
    }
    
    public CelsiusToFahrenheitRequest1(string Celsius) {
        this.Celsius = Celsius;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CelsiusToFahrenheitResponse1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3schools.com/webservices/", Order=0)]
    public string @string;
    
    public CelsiusToFahrenheitResponse1() {
    }
    
    public CelsiusToFahrenheitResponse1(string @string) {
        this.@string = @string;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface TempConvertHttpPostChannel : TempConvertHttpPost, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TempConvertHttpPostClient : System.ServiceModel.ClientBase<TempConvertHttpPost>, TempConvertHttpPost {
    
    public TempConvertHttpPostClient() {
    }
    
    public TempConvertHttpPostClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public TempConvertHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FahrenheitToCelsiusResponse1 TempConvertHttpPost.FahrenheitToCelsius(FahrenheitToCelsiusRequest1 request) {
        return base.Channel.FahrenheitToCelsius(request);
    }
    
    public string FahrenheitToCelsius(string Fahrenheit) {
        FahrenheitToCelsiusRequest1 inValue = new FahrenheitToCelsiusRequest1();
        inValue.Fahrenheit = Fahrenheit;
        FahrenheitToCelsiusResponse1 retVal = ((TempConvertHttpPost)(this)).FahrenheitToCelsius(inValue);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CelsiusToFahrenheitResponse1 TempConvertHttpPost.CelsiusToFahrenheit(CelsiusToFahrenheitRequest1 request) {
        return base.Channel.CelsiusToFahrenheit(request);
    }
    
    public string CelsiusToFahrenheit(string Celsius) {
        CelsiusToFahrenheitRequest1 inValue = new CelsiusToFahrenheitRequest1();
        inValue.Celsius = Celsius;
        CelsiusToFahrenheitResponse1 retVal = ((TempConvertHttpPost)(this)).CelsiusToFahrenheit(inValue);
        return retVal.@string;
    }
}
